title: UFPR-OPT
tagline: Optimization Group of the Federal University of Paraná
author: Abel Soares Siqueira
email: abel.s.siqueira@gmail.com
description: "UFPR's Optimization Group"
keywords: "Optimization"
baseurl: ""
url: "http://ufpr-opt.github.io/" # the base hostname & protocol for your site

markdown: kramdown
