title: Analysis and PDE Group of the Federal University of Paraná - UFPR
author: Fernando de Avila Silva
email: favilasi@gmail.com
description: "UFPR's Analysis and PDE  Group"
baseurl: ""
url: "http://ufpr-pde.github.io/" # the base hostname & protocol for your site

markdown: kramdown
